name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Run security audit
        run: pnpm audit --json > security-audit.json || true
        
      - name: Check for updates
        run: npx npm-check-updates -u
        
      - name: Install updated dependencies
        run: pnpm install
        
      - name: Type check
        run: pnpm run typecheck || echo "Type check failed, but continuing"
        
      - name: Lint check
        run: pnpm run lint || echo "Lint check failed, but continuing"
        
      - name: Build application
        run: pnpm run build
        
      - name: Run tests
        run: pnpm run test:unit || echo "Tests failed, but continuing"
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            This PR updates project dependencies to their latest versions.
            
            ## Changes
            - Updated dependencies to latest versions
            - Build verified
            ${GITHUB_OUTPUT//*security-audit.json*/- Security audit review required\n/}
            
            Please review carefully before merging.
          branch: 'chore/dependency-updates'
          base: 'develop'  # Target the develop branch
          labels: 'dependencies,automated pr'